#!/bin/sh

#DEBHELPER#
usermod -a -G percona-telemetry postgres

mkdir /usr/local/percona/telemetry/pg
chown postgres:percona-telemetry /usr/local/percona/telemetry/pg
chmod 775 /usr/local/percona/telemetry/pg
chmod g+s /usr/local/percona/telemetry/pg
chmod u+s /usr/local/percona/telemetry/pg
exit 0

