#!/bin/sh

#DEBHELPER#

mkdir /usr/local/percona/telemetry/pg
chown postgres:percona-telemetry /usr/local/percona/telemetry/pg
chmod 775 /usr/local/percona/telemetry/pg
chmod g+s /usr/local/percona/telemetry/pg
chmod u+s /usr/local/percona/telemetry/pg
chgrp percona-telemetry /usr/local/percona/telemetry_uuid
chmod 664 /usr/local/percona/telemetry_uuid
exit 0

